In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3, 4, 5])              # из списка
b = np.array([[1, 2, 3], [4, 5, 6]])       # двумерный массив

zeros_arr = np.zeros((2, 3))               # массив из нулей
ones_arr = np.ones((3, 3))                 # массив из единиц
c = np.arange(0, 10, 2)                    # 0, 2, 4, 6, 8

print(a)
print(b)
print(zeros_arr)
print(ones_arr)
print(c)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


In [3]:
print("shape a:", a.shape)
print("dtype a:", a.dtype)

print("shape b:", b.shape)
print("dtype b:", b.dtype)


shape a: (5,)
dtype a: int64
shape b: (2, 3)
dtype b: int64


In [4]:
elem = b[1, 2]           # второй ряд, третий столбец
slice_a = a[1:4]         # элементы со 2-го по 4-й
sub_b = b[0:2, 0:2]      # подмассив 2x2

print("b[1, 2] =", elem)
print("a[1:4] =", slice_a)
print("sub_b =\n", sub_b)


b[1, 2] = 6
a[1:4] = [2 3 4]
sub_b =
 [[1 2]
 [4 5]]


In [5]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print("x + y =", x + y)        # поэлементное сложение
print("x * y =", x * y)        # поэлементное умножение

print("mean x =", x.mean())    # среднее
print("sum x =", x.sum())      # сумма
print("max x =", x.max())      # максимум


x + y = [11 22 33 44]
x * y = [ 10  40  90 160]
mean x = 2.5
sum x = 10
max x = 4
